"""empty message

Revision ID: 2b41e8482f0b
Revises: 7283663ca980
Create Date: 2022-05-31 12:03:22.212970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b41e8482f0b'
down_revision = '7283663ca980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column(
        'seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_description')
    # ### end Alembic commands ###
