"""empty message

Revision ID: 7283663ca980
Revises: b96c5fb100aa
Create Date: 2022-05-31 11:54:01.989111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7283663ca980'
down_revision = 'b96c5fb100aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link',
                  sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column(
        'seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###
